import Navbar from "components/Menu/Navbar";
import Head from "next/head";
import Image from "next/image";
import styles from "styles/Home.module.css";

import en from "locales/en";
import da from "locales/da";
import de from "locales/de";
import { useRouter } from "next/router";

export default function About() {
   //Skift sprog i18n
   const router = useRouter();
   const { locale } = router;
   const t = 
   locale === "da" ? da : locale === "de" ? de : locale === "en" ? en: "";

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div>

        {t.test}
      </div>
    </div>
  );
}
