import Navbar from "components/Menu/Navbar2";
import Head from "next/head";
import en from "locales/en";
import da from "locales/da";
import de from "locales/de";
import { useRouter } from "next/router";
import Footer from "components/Menu/Footer";
import TopHero from "components/Hero/TopHero";

export default function BlivUdlejer() {
  //Skift sprog i18n
  const router = useRouter();
  const { locale } = router;
  const t =
    locale === "da" ? da : locale === "de" ? de : locale === "en" ? en : "";

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <TopHero
        overtitle="Udlej dit"
        // bottomtitle="og tjen penge til at nyde livet"
        bottomtitle="sommerhus"
        span="Og tjen penge til at nyde familien"
        className="bg-[url('/heroudlejer.jpg')] "
        className2="bg-opacity-50 bg-black pt-10 pb-10 lg:pb-0 lg:pt-0"
      />

      <Footer />
    </div>
  );
}
