import Navbar2 from "components/Menu/Navbar2";
import Head from "next/head";
import Image from "next/image";
import styles from "styles/Home.module.css";
import Link from "next/link";

import en from "locales/en";
import da from "locales/da";
import de from "locales/de";
import { useRouter } from "next/router";
import Footer from "components/Menu/Footer";
import TopHero from "components/Hero/TopHero";
import CityFeatures from "components/SecondaryFeatures/CityFeatures";


export default function Home() {
  //Skift sprog i18n
  const router = useRouter();
  const { locale } = router;
  const t =
    locale === "da" ? da : locale === "de" ? de : locale === "en" ? en : "";

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <Navbar2 />
      <TopHero />

      <CityFeatures />

      <Footer />
    </div>
  );
}
